### ISSUE TITLE
Segfault on LINUX64 when running with -dedicated

### ISSUE THREAD

**Issue by tatokis** [STJr/SRB2#11]
Running SRB2 (2.1.8) with -dedicated on Ubuntu 14.04 amd64, with srb2 compiled for SDL 1.2.15 results in a segfault.
CPU is AMD FX 8350, with Radeon HD7870 (fglrx 14.4) graphics card and 16GB of system RAM.
Investigating with gdb gave more information about the segfault, seems to be caused  by libSDL-1.2.so
Here's the output from the console:

Reading symbols from lsdlsrb2.debug...done.
(gdb) set args -dedicated
(gdb) run
Starting program: /media/tatokis/Data/srb2new/lsdlsrb2.debug -dedicated
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Compiled for SDL version: 1.2.15
Linked with SDL version: 1.2.15
Setting up SRB2...
M_StartupLocale...
Looking for WADs in: SRB2WADDIR,.
Z_Init(): Init zone memory allocation daemon. 
System memory: 48MB - Free: 48MB
I_StartupTimer()...
W_InitMultipleFiles(): Adding IWAD and main PWADs.
Added file /media/tatokis/Data/srb2new/srb2.srb (6190 lumps)
Loading main config from /media/tatokis/Data/srb2new/srb2.srb
Added file /media/tatokis/Data/srb2new/zones.dta (960 lumps)
Loading main config from /media/tatokis/Data/srb2new/zones.dta
Added file /media/tatokis/Data/srb2new/player.dta (526 lumps)
Added file /media/tatokis/Data/srb2new/rings.dta (444 lumps)
Added file /media/tatokis/Data/srb2new/patch.dta (30 lumps)
Added file /media/tatokis/Data/srb2new/music.dta (171 lumps)
I_StartupGraphics()...
CPU Info: 486: 0, 586: 1, MMX: 1, 3DNow: 0, MMXExt: 1, SSE2: 1
HU_Init(): Setting up heads up display.
The server has lifted the forced skin restrictions.
couldn't execute file /home/tatokis/.srb2/dconfig.cfg

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b720ea in SDL_ListModes ()
   from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
(gdb)

**Comment by ToontownLittleCat** [comment]
Couldn't replicate the error.  (Ubuntu 14.04 64-bit) Maybe it's fixed already?

**Comment by Furyhunter** [comment]
It has been fixed since SDL2 was merged in. The issue should be marked as closed.
