### ISSUE TITLE
fixing 64bit netgame issues

### ISSUE THREAD

**Issue by JJK96** [STJr/SRB2#139]
I noticed that 64bit builds are not netgame compatible with 32bit builds, I would like to try and fix this
Can this issue be easily solved or would we need to rewrite the whole netgame code?
If it can be solved could you point me in the right direction and show me how I can get more debug output?

**Comment by RedEnchilada** [comment]
The major problem that I know of is, IIRC, we don't have actual serialization code for data structures and just rely on how the compiler packs structs when we tell it to.

**Comment by SteelTitanium** [comment]
So since #259 was recently merged, which fixes a bug that allows cross architecture play between the official 32-bit ASM build and 64-but builds. This is no longer an issue, right? Unless another issue pops up.

**Comment by JJK96** [comment]
That is good news, I guess this issue can be closed then
