### ISSUE TITLE
DOS version of SRB2 will not load

### ISSUE THREAD

**Issue by rdrpenguin04** [STJr/SRB2#206]
The DOS Version of SRB2 will not load, despite using DPMI.

Output:

> Exiting due to signal SIGSEGV
> Page fault at eip=000b737b, error=0004
> eax=00000000 ebx=00000000 ecx=10007025 edx=00000000 esi=00000000 edi=00326b7b
> ebp=00326a38 esp=00326a10 program=C:\SRB2\SRB2W16.EXE
> cs: sel=00a7  base=10000000  limit=0032ffff
> ds: sel=00af  base=10000000  limit=0032ffff
> es: sel=00af  base=10000000  limit=0032ffff
> fs: sel=008f  base=00001a20  limit=0000ffff
> gs: sel=00bf  base=00000000  limit=0010ffff
> ss: sel=00af  base=10000000  limit=0032ffff
> App stack: [00326c68...002a6c68]  Exceptn stack: [002a6b94...002a4c54]
> 
> Call frame traceback EIPs:
>   0x000b737b
>   0x000b1bc1
>   0x00002ee7
>   0x00001f7b
>   0x0014ca27

Running DOSBox version 0.74 on Linux 64-bit.
By the way, nice error handler!
If there is anything else you need, let me know.

**Comment by toasterone** [comment]
Appreciated that you've taken the time to leave an issue on the tracker about this, and extremely sorry about the amount of time we took to get back to you, but DOS is not an actively supported platform. It currently only exists in the source as a historical anquity, and as such, I'm afraid I have to close this.

The platforms we actually try to support are Win32, Intel Mac, and Linux.
