### ISSUE TITLE
SRB2 won’t open

### ISSUE THREAD

**Issue by MailBoxSNES** [STJr/SRB2#225]
When ever I run SRB2 it doesn’t open anymore, this happened 2 days ago and now I can’t play the game anymore. :^(

**Comment by Malcolm002** [comment]
Forgot to list my pc specs
Windows vista sp1 32-bit

**Comment by MonsterIestyn** [comment]
whoops, didn't notice your issue until now, what does it do when it tries to open?

(btw 2.1.20 just came out, maybe you'll have better luck this time, I have no idea)

**Comment by Malcolm002** [comment]
Ok

**Comment by Malcolm002** [comment]
Nope it still won’t run even though I have the latest update

**Comment by Malcolm002** [comment]
1. It show up in task manager but does not open
2. It gradually slows down the pc
3. It causes explorer.exe to stop responding forcing me to reset my pc

This was not happing to me before.

**Comment by MonsterIestyn** [comment]
Hm, that does sound strange. Do you remember if anything changed on your computer on the same day SRB2 stopped working properly, or the day before?

**Comment by Malcolm002** [comment]
I can tell you what exactly happened, I tried to connect to a 2.0 server but it wouldn’t connect i tried so many times and then the server disappeared so then I try to play 2.1 and I noticed I was not opening, I thought it was a usual delay to open the game but it was not opening at all, so that’s what happened.

**Comment by Malcolm002** [comment]
And not to mention that I allowed the anti virus to my computer I still had the same issue

**Comment by toasterone** [comment]
Hi! I just want to confirm - does this still continue to happen? Or has it fixed itself with subsequent Windows patches?

**Comment by MailBoxSNES** [comment]
No I haven’t tried it on that computer yet but I got a new laptop so I’m playing it on there, I don’t have that problem on my new pc.

**Comment by toasterone** [comment]
Alright. Reading up at your description, I have a suspicion as to the problem - on your old computer, are your SRB2 2.0 and SRB2 2.1 installs in the same folder?
