### ISSUE TITLE
"No package 'libgme' found", in spite of libgme being installed

### ISSUE THREAD

**Issue by yyyyyyyx** [STJr/SRB2#240]
I was trying to build 2.1 on linux, and I just got this error message:

`No package 'libgme' found
Package libgme was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgme.pc'
to the PKG_CONFIG_PATH environment variable
`
How do I fix this?

**Comment by alama** [comment]
` pkg-config --list-all|grep libgme`
also, what OS?

**Comment by toasterone** [comment]
Hi! I just want to check - is this still an issue?

**Comment by JojoMasterofDojo** [comment]
Uh, has anyone found a solution? I'm trying to install SRB2 as well.

**Comment by alama** [comment]
Well, did you install the  development package of libgme?

**Comment by JojoMasterofDojo** [comment]
Uh, yes. I installed libgme-dev. This is what happens when I try installing it again.
`chrx@chrx:~$ sudo apt-get install libgme-dev
[sudo] password for chrx: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgme-dev is already the newest version (0.6.0-3ubuntu0.16.04.1).
The following packages were automatically installed and are no longer required:
  cabextract libmspack0 p7zip
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.
chrx@chrx:~$ 
`
I'm assuming there is no fix for this then... I'll just emulate the windows version via wine, but it looks like I need OpenGL. Are there any guides for making Wine work with SRB2?

**Comment by alama** [comment]
how about what version and files the package have?
```
$ dpkg -l libgme-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                           Version                      Architecture                 Description
+++-==============================================-============================-============================-==================================================================================================
ii  libgme-dev:amd64                               0.6.2-1                      amd64                        Playback library for video game music files - development files
```

```
$ dpkg -L libgme-dev
/.
/usr
/usr/include
/usr/include/gme
/usr/include/gme/gme.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/share
/usr/share/doc
/usr/share/doc/libgme-dev
/usr/share/doc/libgme-dev/changelog.Debian.gz
/usr/share/doc/libgme-dev/changelog.gz
/usr/share/doc/libgme-dev/copyright
/usr/lib/x86_64-linux-gnu/libgme.so

```

**Comment by JojoMasterofDojo** [comment]
Here is the output for (dpkg -l libgme-dev):

`chrx@chrx:~$ dpkg -l libgme-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libgme-dev:amd 0.6.0-3ubunt amd64        Playback library for video game m
chrx@chrx:~$ `

And the output for (dpkg -L libgme-dev)
`/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libgme-dev
/usr/share/doc/libgme-dev/copyright
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/include
/usr/include/gme
/usr/include/gme/gme.h
/usr/share/doc/libgme-dev/changelog.Debian.gz
/usr/lib/x86_64-linux-gnu/libgme.so`

**Comment by alama** [comment]
ok, so the same as my Debian setup, there no `libgme.pc` file
you have to manually set `LIBGME_CFLAGS` and `LIBGME_LDFLAGS`

```
export LIBGME_CFLAGS=
export LIBGME_LDFLAGS=-lgme
```

Is my guess

**Comment by JojoMasterofDojo** [comment]
Ok, I entered in the commands for the terminal, and so far in the compiling stage I am not getting the same error. Thank you for all of your help, and if there is an error it won't be the same one, I'd probably go to a different forum. Thank you.

**Comment by JojoMasterofDojo** [comment]
Uh, when loading the lsdl2srb2 executable the compiling gave me, it spits out this..
`Compiled for SDL version: 2.0.4
Linked with SDL version: 2.0.4
Setting up SRB2...
Looking for WADs in: SRB2WADDIR,.,/usr/local/share/games/SRB2,/usr/local/games/SRB2,/usr/share/games/SRB2,/usr/games/SRB2,HOME`

Naturally I would just wait but it appears to be taking a really long time, do you have a fix for this? If not, could you direct me somewhere where they might have a fix? I understand that this is not relevant to the problem at all.

**Comment by alama** [comment]
Well, yea, the binary needs the WAD files that is in the Windows installer
for packages, they ship the WAD files to /usr/share/games/SRB2

for you, it will look for the files in the currect folder, then all the games files, look at all of your HOME folder

just place the binary right next to the files and it should load

**Comment by JojoMasterofDojo** [comment]
It worked! Thank you for all of your help. Everything is working smoothly and despite it running on a chromebook, the performance is amazing.
