### ISSUE TITLE
Compiling on 64bit Linux is hilariously broken.

### ISSUE THREAD

**Issue by Theswweet** [STJr/SRB2#43]
Whenever I try to compile according to the readme, I get 

`james@James:~/SRB2$ make -C src LINUX64=1
make: Entering directory '/home/james/SRB2/src'
Creating dependency file, depend.dep
sdl/i_system.c:26:23: fatal error: config.h.in: No such file or directory
 #include "config.h.in"
                       ^
compilation terminated.
sdl/mixer_sound.c:23:23: fatal error: SDL_mixer.h: No such file or directory
 #include "SDL_mixer.h"
                       ^
compilation terminated.
sdl/i_system.c:26:23: fatal error: config.h.in: No such file or directory
 #include "config.h.in"
                       ^
compilation terminated.
Makefile:744: recipe for target '../objs/Linux64/SDL/Release/i_system.o' failed
make: *** [../objs/Linux64/SDL/Release/i_system.o] Error 1
make: Leaving directory '/home/james/SRB2/src'`

**Comment by alama** [comment]
Yea, the old Makefile is broken, had you tried cmake?

http://wiki.srb2.org/wiki/Source_code_compiling#Configuring_and_generating_with_CMake

**Comment by Theswweet** [comment]
Closed this since I got it working with cmake, and some help on the IRC.

**Comment by Theswweet** [comment]
On that note, however - maybe the cmake stuff should be added to the README?
