### ISSUE TITLE
gettext builds crashing on non-English locale

### ISSUE THREAD

**Issue by TatsuruIKR** [STJr/SRB2#438]
Pretty straightforward, although I only had the chance to test with a Brazilian Portuguese MO: a pure gettext build crashes with no error shortly after running `HU_Init`. Replacing strings manually in the code does fine, so it might something to do with parsing the strings?

[srb2win.rpt.txt](https://github.com/STJr/SRB2/files/3658651/srb2win.rpt.txt)

**Comment by alama** [comment]
RPTs are USELESS without the fat DBG file AND source code used to build the EXE

I am BETTING that the FONT do not have the glyph to render the text

**Comment by Ikkarin** [comment]
If that's the case, then it's pretty much settled, I believe.

Here's the file if it's still of any help.
[srb2win.debug.zip](https://github.com/STJr/SRB2/files/3659449/srb2win.debug.zip)
