### ISSUE TITLE
any solution when sega attacks due the art usage?

### ISSUE THREAD

**Issue by mckaygerhard** [STJr/SRB2#452]
maybe soon SEGA wil attack due the usage of the artwork, any contribution on that? seems it's a good game and maybe future problems comes like happened with opensonic http://opensnc.sourceforge.net that continues in opensurge..

**Comment by MonsterIestyn** [comment]
Frankly, if SEGA attacked anyone for using Sonic *artwork* (of all things), let alone us, they have done it many years ago. SRB2 has been developed for over 20 years by now.

As far as SEGA goes with fangames in general, they seem to be generally alright with them unless they involve money in some way. Not like Nintendo at all if that's what you're thinking of.

In any case this isn't really something to make an issue ticket for in our source code, so I'm closing this.
