### ISSUE TITLE
(2.2.1) Can't skip tally screen when spin is set to mouse buttons

### ISSUE THREAD

**Issue by CharmsyPone** [STJr/SRB2#453]
Hey, so I'm lovin the feature that lets you see the mouse on the tally screen and other stuff, not sure what purpose it has, but it's neat.

...but as a result of that, I can't skip the tally screen! I always set spin to mouse 2 because it's most convenient for me to use, but as a result, I can't skip the tally screen.

It's simple to reproduce, just open the game, set the control to spin to mouse2 (or anything else really), go to a tally screen. Can't skip it.

**Comment by LJSonik** [comment]
Try `alwaysgrabmouse off` in the console.
Guess I should make this a menu option instead of just a variable.

**Comment by CharmsyPone** [comment]
Yeah that's a good solution for the time being if a fix can't be put into 2.2.1, cuz I know I'm awfully late on reporting this.

(though, shouldn't it be "on"? the implication being that if it's on, it always grabs the mouse)

**Comment by LJSonik** [comment]
Yes, I meant "on" sorry.

I am honestly not so eager to make a "fix" for this, because being able to move your mouse during intermissions makes a lot of sense.
SRB2 has an option to allow several keys per control, maybe you could set an alternate key for spinning?
