### ISSUE TITLE
Issue on Egg Rock Zone Act 2

### ISSUE THREAD

**Issue by PoggersPlayer** [STJr/SRB2#494]
Trouble on Egg Rock Zone 2. When there's red cross following but the it doesn't spin into hole correctly. See this.
![srb20015](https://user-images.githubusercontent.com/87897010/132148872-3fa787ef-f6b6-4d50-9ac7-2e1bd00b233f.gif)

**Comment by lachwright** [comment]
It's not an automatic spin tube, you're supposed to walk forward into the next ring trail so that you get flipped into the next section.
