### ISSUE TITLE
Models aren't loading / don't appear to be working on Flatpak build

### ISSUE THREAD

**Issue by MugofBro** [STJr/SRB2#517]
Self explanatory, enabling models in the Flatpak version of the application does not appear to be loading them. I tried digging around in the files and I noticed that a models.dat didn't appear to be included, so I'm unsure if that is the cause.

**Comment by SteelT1** [comment]
Any issues related to the flatpak build should be reported [here](https://github.com/flathub/org.srb2.SRB2/issues), as it is not maintained by us.
